CREATE TABLE users (
id SERIAL PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
senha_hash VARCHAR(255) NOT NULL,
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id) NOT NULL,
conteudo TEXT NULL,
imagem_url VARCHAR(255) NULL,
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
id SERIAL PRIMARY KEY,
post_id INTEGER REFERENCES posts(id) NOT NULL,
user_id INTEGER REFERENCES users(id) NOT NULL,
conteudo TEXT NULL,
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE likes(
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id) NOT NULL,
post_id INTEGER REFERENCES posts(id) NOT NULL,
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UNIQUE (user_id, post_id)
);

CREATE TABLE follows(
id SERIAL PRIMARY KEY,
follower_id INTEGER REFERENCES users(id) NOT NULL,
following_id INTEGER REFERENCES users(id) NOT NULL,
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UNIQUE (follower_id, following_id)
);
